[project]
name = "comfyui-dhan-smart-memory-override"
version = "1.0.0"
description = "Manual Smart Memory control nodes for ComfyUI."
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/DHan315/Comfyui-DHan-Smart-Memory-Override"
"Bug Tracker" = "https://github.com/DHan315/Comfyui-DHan-Smart-Memory-Override/issues"

[tool.comfy]
PublisherId = "dhan315"
DisplayName = "Comfyui-DHan-Smart-Memory-Override"
